# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -- Namespace for the deployment
namespace: processing

service:
  # -- Port for the service
  port: 8080

app:
  # -- Port for the application
  port: 8080
  # -- OIDC End Point
  oidc_endpoint: "https://iam.{{ platform_domain_name }}"
  # -- OIDC Realm
  oidc_realm: "rspy"
  # -- OIDC Public Client ID
  oidc_client_id: "fastapi_public"
  # -- Allows or disallows loading and browsing external STAC data
  SB_allowExternalAccess: "false"
  # -- Detect locale from user
  SB_detectLocaleFromBrowser: "true"
  # -- Allows search engines to better crawl STAC Browser. Must be set to 'history' for OIDC
  SB_historyMode: history
  # -- Social sharing
  SB_socialSharing: "email,bsky,mastodon"
  # -- URL of the STAC catalog
  SB_catalogUrl: https://{{ platform_domain_name }}/cadip/

# -- Pod affinity
affinity:
  nodeAffinity:
   requiredDuringSchedulingIgnoredDuringExecution:
     nodeSelectorTerms:
     - matchExpressions:
       - key: node-role.kubernetes.io/rs_server
         operator: Exists

# -- Pod toleration
tolerations:
  - key: role
    value: rs_server
    effect: NoSchedule

ingress:
  # -- Enabled/Disable ingress
  enabled: true
  issuer:
    # -- Ingress Issuer type
    type: cluster-issuer
    # -- Ingress Issuer name
    name: letsencrypt-prod
  # -- Ingress host name.
  host: stac-browser-cadip.{{ platform_domain_name }}
  # -- Ingress path for the application
  # Note that because of bug https://github.com/radiantearth/stac-browser/issues/479 the path is forced to /
  path: /
