# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -- Namespace for the deployment
namespace: processing

app:
  # -- Port for the application
  port: 8000
  # -- URL of the API Key Manager service
  uacURL: http://apikeymanager.processing.svc.cluster.local:8000/auth/check_key
  # -- Object Storage bucket for the catalog
  catalogBucket: {{ rspy.catalog_bucket }}
  uacHomeUrl : https://apikeymanager.{{ platform_domain_name }}/docs

auth:
  secret:
    # -- OIDC End Point
    oidc_endpoint: "https://iam.{{ platform_domain_name }}"
    # -- OIDC Realm
    oidc_realm: "rspy"
    # -- OIDC CLient ID
    oidc_client_id: "apikeymanager"
    # -- OIDC Secret used to sync user info from Keycloak
    oidc_client_secret: "{{ apikeymanager_oidc_client_secret }}"
    # -- Random string used to encode cookie-based HTTP sessions in SessionMiddleware
    cookie_secret: "{{ rsserver_cookieSecret }}"

postgres:
  # -- PostgreSQL port
  port: "5432"
  # -- PostgreSQL database name
  db: {{ rs_server_catalog.database.name }}
  host:
    # -- PostgreSQL service URL for Read Write
    rw: {{ rs_server_catalog.database.host }}
    # -- PostgreSQL service URL for Read Only
    ro: {{ rs_server_catalog.database.host }}
  secret:
    # -- Username to authenticate with the PostgreSQL service
    user: {{ rs_server_catalog.database.username }}
    # -- Password to authenticate with the PostgreSQL service
    pass: {{ rs_server_catalog.database.password }}

obs:
  # -- URL of the object storage service endpoint
  endpoint: {{ s3.endpoint }}
  # -- Region of the object storage service
  region: {{ s3.region }}
  secret:
    # -- Access Key to authenticate with the object storage service
    ak: {{ s3.access_key }}
    # -- Secret Key to authenticate with the object storage service
    sk: {{ s3.secret_key }}

ingress:
  # -- Enabled/Disable ingress
  enabled: true
  issuer:
    # -- Ingress Issuer type
    type: cluster-issuer
    # -- Ingress Issuer name
    name: letsencrypt-prod
  # -- Ingress host name
  host: {{ platform_domain_name }}
  # -- Ingress path
  path:
    - /catalog
    - /auth

stac_browser:
  urls: "https://stac-browser-auxip.{{ platform_domain_name }};https://stac-browser-cadip.{{ platform_domain_name }};https://stac-browser-catalog.{{ platform_domain_name }}"