# Copyright 2025 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -- Namespace where to deploy the ConfigMap
namespace: processing

# -- Name to give to the configuration file
bucketConfigFileName: expiration_bucket.csv

# -- Bucket configuration
# Format :
# <owner>,<collection>,<eopf:type>,<expiration delay>,<bucket name>
expiration_bucket_csv: |
    *,*,*,30,prip-rs-playground
    redirect-gsanom,*,*,90,gsanom-share
    copernicus,*,*,30,prip-rs-sentinel-default
    copernicus,*,*ADF*,7300,prip-rs-sentinel-aux-infinite
    copernicus,s01-aux-*,*,30,prip-rs-sentinel-1-s01-aux
    copernicus,s01-cadip-session,*,30,prip-rs-sentinel-1-s01-session
    copernicus,s01-edip-session,*,30,prip-rs-sentinel-1-s01-session
    copernicus,s02-aux-*,*,30,prip-rs-sentinel-2-s02-aux
    copernicus,s02-cadip-session,*,30,prip-rs-sentinel-2-s02-session
    copernicus,s02-edip-session,*,30,prip-rs-sentinel-2-s02-session
    copernicus,s03-aux-*,*,30,prip-rs-sentinel-3-s03-aux
    copernicus,s03-cadip-session,*,30,prip-rs-sentinel-3-s03-session
    copernicus,s01siwraw,*,30,prip-rs-sentinel-1-s01siwraw
    copernicus,s01sewraw,*,30,prip-rs-sentinel-1-s01sewraw
    copernicus,s01ssmraw,*,30,prip-rs-sentinel-1-s01ssmraw
    copernicus,s01swvraw,*,30,prip-rs-sentinel-1-s01swvraw
    copernicus,s01siwanc,*,30,prip-rs-sentinel-1-s01siwanc
    copernicus,s01sewanc,*,30,prip-rs-sentinel-1-s01sewanc
    copernicus,s01ssmanc,*,30,prip-rs-sentinel-1-s01ssmanc
    copernicus,s01swvanc,*,30,prip-rs-sentinel-1-s01swvanc
    copernicus,s01sewgrd,*,30,prip-rs-sentinel-1-s01sewgrd
    copernicus,s01siwgrd,*,30,prip-rs-sentinel-1-s01siwgrd
    copernicus,s01ssmgrd,*,30,prip-rs-sentinel-1-s01ssmgrd
    copernicus,s01swvgrd,*,30,prip-rs-sentinel-1-s01swvgrd
    copernicus,s01sewocn,*,30,prip-rs-sentinel-1-s01sewocn
    copernicus,s01siwocn,*,30,prip-rs-sentinel-1-s01siwocn
    copernicus,s01ssmocn,*,30,prip-rs-sentinel-1-s01ssmocn
    copernicus,s01swvocn,*,30,prip-rs-sentinel-1-s01swvocn
    copernicus,s01sewslc,*,30,prip-rs-sentinel-1-s01sewslc
    copernicus,s01siwslc,*,30,prip-rs-sentinel-1-s01siwslc
    copernicus,s01ssmslc,*,30,prip-rs-sentinel-1-s01ssmslc
    copernicus,s01swvslc,*,30,prip-rs-sentinel-1-s01swvslc
    copernicus,s01srfraw,*,30,prip-rs-sentinel-1-s01srfraw
    copernicus,s01senraw,*,30,prip-rs-sentinel-1-s01senraw
    copernicus,s01sanraw,*,30,prip-rs-sentinel-1-s01sanraw
    copernicus,s01szmraw,*,30,prip-rs-sentinel-1-s01szmraw
    copernicus,s01sziraw,*,30,prip-rs-sentinel-1-s01sziraw
    copernicus,s01szeraw,*,30,prip-rs-sentinel-1-s01szeraw
    copernicus,s01szwraw,*,30,prip-rs-sentinel-1-s01szwraw
    copernicus,s01s__obs,*,30,prip-rs-sentinel-1-s01sxxobs
    copernicus,s01gpsraw,*,30,prip-rs-sentinel-1-s01gpsraw
    copernicus,s01hkmraw,*,30,prip-rs-sentinel-1-s01hkmraw
    copernicus,s01aisraw,*,30,prip-rs-sentinel-1-s01aisraw
    copernicus,s02msil0_,*,30,prip-rs-sentinel-2-s02msil0x
    copernicus,s02msil1a,*,30,prip-rs-sentinel-2-s02msil1a
    copernicus,s02msil1b,*,30,prip-rs-sentinel-2-s02msil1b
    copernicus,s02msil1c,*,30,prip-rs-sentinel-2-s02msil1c
    copernicus,s02msil2a,*,30,prip-rs-sentinel-2-s02msil2a
    copernicus,s02msisca,*,30,prip-rs-sentinel-2-s02msisca
    copernicus,s02msidca,*,30,prip-rs-sentinel-2-s02msidca
    copernicus,s02hkmraw,*,30,prip-rs-sentinel-2-s02hkmraw
    copernicus,s02sadl0_,*,30,prip-rs-sentinel-2-s02sadl0x
    copernicus,s03dordop,*,30,prip-rs-sentinel-3-s03dordop
    copernicus,s03dornav,*,30,prip-rs-sentinel-3-s03dornav
    copernicus,s03gnsl0_,*,30,prip-rs-sentinel-3-s03gnsl0x
    copernicus,s03altl0_,*,30,prip-rs-sentinel-3-s03altl0x
    copernicus,s03sral0c,*,30,prip-rs-sentinel-3-s03sral0c
    copernicus,s03altl1a,*,30,prip-rs-sentinel-3-s03altl1a
    copernicus,s03altl1b,*,30,prip-rs-sentinel-3-s03altl1b
    copernicus,s03altl1r,*,30,prip-rs-sentinel-3-s03altl1r
    copernicus,s03altl2h,*,30,prip-rs-sentinel-3-s03altl2h
    copernicus,s03altl2l,*,30,prip-rs-sentinel-3-s03altl2l
    copernicus,s03altl2s,*,30,prip-rs-sentinel-3-s03altl2s
    copernicus,s03altcal,*,30,prip-rs-sentinel-3-s03altcal
    copernicus,s03mwrl0_,*,30,prip-rs-sentinel-3-s03mwrl0x
    copernicus,s03mwrl1_,*,30,prip-rs-sentinel-3-s03mwrl1x
    copernicus,s03mwrcal,*,30,prip-rs-sentinel-3-s03mwrcal
    copernicus,s03olccr0,*,30,prip-rs-sentinel-3-s03olccr0
    copernicus,s03olccr1,*,30,prip-rs-sentinel-3-s03olccr1
    copernicus,s03olcl0_,*,30,prip-rs-sentinel-3-s03olcl0x
    copernicus,s03olcefr,*,30,prip-rs-sentinel-3-s03olcefr
    copernicus,s03olcerr,*,30,prip-rs-sentinel-3-s03olcerr
    copernicus,s03olcrac,*,30,prip-rs-sentinel-3-s03olcrac
    copernicus,s03olcspc,*,30,prip-rs-sentinel-3-s03olcspc
    copernicus,s03olclfr,*,30,prip-rs-sentinel-3-s03olclfr
    copernicus,s03olclrr,*,30,prip-rs-sentinel-3-s03olclrr
    copernicus,s03slsl0_,*,30,prip-rs-sentinel-3-s03slsl0x
    copernicus,s03slsrbt,*,30,prip-rs-sentinel-3-s03slsrbt
    copernicus,s03slslst,*,30,prip-rs-sentinel-3-s03slslst
    copernicus,s03slsfrp,*,30,prip-rs-sentinel-3-s03slsfrp
    copernicus,s03synsdr,*,30,prip-rs-sentinel-3-s03synsdr
    copernicus,s03synmis,*,30,prip-rs-sentinel-3-s03synmis
    copernicus,s03synaod,*,30,prip-rs-sentinel-3-s03synaod
    copernicus,s03synvgt,*,30,prip-rs-sentinel-3-s03synvgt
    copernicus,s03synvgk,*,30,prip-rs-sentinel-3-s03synvgk
    copernicus,s03synv01,*,30,prip-rs-sentinel-3-s03synv01
    copernicus,s03synv10,*,30,prip-rs-sentinel-3-s03synv10
    copernicus,s03hkml0_,*,30,prip-rs-sentinel-3-s03hkml0x
    copernicus,s03hkmraw,*,30,prip-rs-sentinel-3-s03hkmraw
    copernicus,s03hkm2l0,*,30,prip-rs-sentinel-3-s03hkm2l0
    copernicus,s03natl0_,*,30,prip-rs-sentinel-3-s03natl0x

